### ISSUE TITLE
API design of stencil.Delete vs stencil.RemoveAll

### ISSUE THREAD

**Issue by samnguyen-outreach** [getoutreach/stencil#145]
Just some feedback:

`stencil.Delete` is a bit awkward to use, since it's stateful - you have to run `stencil.Create` and then `stencil.Delete`.

It's also analogous to `stencil.RemoveAll`, but RemoveAll takes an argument and Delete does not. 

My request would be to allow Delete to take an argument (perhaps an optional one if you can't break compatibility).

**Comment by jaredallard** [comment]
Do you mean `file.Delete`? The idea behind that was to keep everything centric to the current "file" which is what `file` is scoped to. `stencil` functions are meant to be not scoped to a single file, and thus `RemoveAll`, and `Exists` are set there.

That being said, I can't really think of something better than the current `file.Delete` paradigm, or just using `stencil.RemoveAll` instead.

**Comment by samnguyen-outreach** [comment]
Whoops, yes I meant `file.Delete` and didn't even think of just using `stencil.RemoveAll` directly...I was thinking it was only for directories.  That basically does what I want.   Thanks Jared.
