### ISSUE TITLE
stencil describe can't find file

### ISSUE THREAD

**Issue by samnguyen-outreach** [getoutreach/stencil#157]
Looks like it is looking for the exact path from stencil.lock, but the behavior is a little surprising, as I would expect it to accept a reasonable looking file path as well

```
❯ stencil describe cmd/smartstorecdctestconsumer/smartstore.go
cmd/smartstorecdctestconsumer/smartstore.go was created by module https://github.com/getoutreach/stencil-smartstore (template: cmd/smartstore.go.tpl)

❯ stencil describe ./cmd/smartstorecdctestconsumer/smartstore.go
ERRO[0000] failed to run: file "./cmd/smartstorecdctestconsumer/smartstore.go" isn't created by stencil
```

**Comment by jaredallard** [comment]
Ah, good catch. We should probably just run the input through `filepath.Clean()` + handle abs, and then trim the `./` (if present)
