### ISSUE TITLE
https://github.com/getoutreach/stencil-discovery not accessible

### ISSUE THREAD

**Issue by rdtechie** [getoutreach/stencil#204]
Hi, I'm going through the documentation and I'm trying to create a module.
However I'm getting this error:

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/6579452/213865404-89eade38-34eb-4b56-b693-74bd135daa5e.png">

Error message in text:
`failed to get versions for "https://github.com/getoutreach/stencil-discovery": failed to git ls-remote "https://github.com/getoutreach/stencil-discovery": repository not found `

**Comment by jaredallard** [comment]
Looks like we have a private dependency being used when we shouldn't 😢 We'll work on getting this fixed asap!

**Comment by rdtechie** [comment]
What is the status on this?

**Comment by jaredallard** [comment]
> What is the status on this?

We're working on it! It's been a bit more work than we anticipated. Will update the issue soon :)

**Comment by jaredallard** [comment]
This _should_ be resolved now, sorry for the delayed update. We're working on some other issues that we've managed to reproduce in this process as well. Will keep this issue thread updated!

**Comment by jaredallard** [comment]
From your new issue, it looks like we're past this one, right? If so, going to close this out and focus on the next one.

**Comment by rdtechie** [comment]
Seem so! Thanks!
